### ISSUE TITLE
Waterbirth Dungeon not Recognized as a Fremennik Region

### ISSUE THREAD

**Issue by tylerthardy** [dekvall/runelite-external-plugins#12]
![image](https://user-images.githubusercontent.com/17709869/98777478-7510fe00-23b6-11eb-8b43-8b9b9dcdeebd.png)

Teleporting from the Waterbirth dungeon doesn't add the overlay.

**Comment by dekvall** [comment]
Thanks, fixed in 3ec559ca241a3b408defc8091dff017e69289d4d.
