### ISSUE TITLE
[WOM Utils] Some suggestions to discuss after this "beta" period

### ISSUE THREAD

**Issue by psikoi** [dekvall/runelite-external-plugins#16]
Regarding the current (first) version of Wom utils, there's a couple things that could be improved:

- Change plugin name (?) to "Wise Old Man" / "WiseOldMan" or at the very list capitalize it as "WOM Utils"
- Change plugin image
- Change plugin description (maybe something a little more descriptive)
- Change capitalization of the word "member" for both Add and Remove actions
- Change error messages to contain the prefix "Error:" just to make it a little more obvious
- Change success messages' color to green

One thing that could also be improved is a visual way to tell if some cc player is on the group or not (so you could quickly scan the cc and see who's missing). An idea someone suggested to me was to color members/nonmembers differently.

Maybe the group members could be WOM-blue? Idk

**Comment by dekvall** [comment]
Fixed by #17
