### ISSUE TITLE
[World Hider] Plugin takes a short time to activate after switching to the Friends Tab

### ISSUE THREAD

**Issue by Hydrox6** [dekvall/runelite-external-plugins#2]
This kind of defeats the point of the plugin, sadly. Clan Chat seems to work perfectly fine though.

**Comment by dekvall** [comment]
This had to do with interferance from the friends list plugin, and i have made it update the text on client tick. It still flickers a little, but i was unable to register the real world. Another option is to disable the friendslistplugin when using world hider.
