### ISSUE TITLE
[wise-old-man] Competition reminder and display

### ISSUE THREAD

**Issue by Enriath** [dekvall/runelite-external-plugins#30]
Currently, competitions one WOM count XP gained after the first snapshot after it starts. This can be problematic if a user forgets to set a baseline before actually starting to compete (see [this](https://discord.com/channels/679454777708380161/696219355138228254/833696324675305573)).

While discussing automation possibilities for this, it was mentioned that the plugin could notify the user if they're in a competition but haven't got a baseline set. The plugin should probably try to do it for them, but it really should be visible what's going on, and it should tell them if it goes wrong so they can fix it before they log out and submit their first chunk of competition xp. 

And since it would be tracking some competition stuff, being able to display competition information to the user (maybe on and overlay) would be nice to see in the plugin, so a user could track maybe their total gains (vs reported gains) and a mini leaderboard (top X and the player's pos, or something)

Discord convo for reference [here](https://discord.com/channels/679454777708380161/696219355138228254/834113407091343412).

**Comment by dekvall** [comment]
Semi-implemented at 53624073e56a79a942df074fb442d447eb1c5631
