### ISSUE TITLE
Missing "A B R E N" interactions and can't interact with bankers or GE people.

### ISSUE THREAD

**Issue by ltmetalman** [dekvall/runelite-external-plugins#31]
When I tried this app, it made it so that all bankers and GE people had two instances of "Examine" on the user interactions.
The message in my game chat says that I am missing A B R E N (Capital letters in red). I have no idea what that is, there are only two settings I can control, and I don't really like either. So I uninstalled it, thinking it will break my game...

![abren](https://user-images.githubusercontent.com/54198179/119224730-7c336a00-bac5-11eb-8b48-22bc6b2f8cb3.JPG)

**Comment by dekvall** [comment]
Inventory Scrabble is a gamemode plugin which requires you to have certain items in your inventory in order to interact with NPCs, in this case you are missing items with names that begin with A, B, R, E and N.
