### ISSUE TITLE
[Wise Old Man] Auto submitted name changes are all lowercase

### ISSUE THREAD

**Issue by BoomOSRS** [dekvall/runelite-external-plugins#37]
Name changes submitted by the WOM RuneLite plugin are currently always all lowercase.
In the name-changes file, it seems to submit name changes with the correct capitalization. For example:  `"PecanVibes11":"PecanBread11"`
However, the name is then displayed as `pecanvibes11` on the site.

If I was to manually submit a name change on the site https://wiseoldman.net/names/submit
The name would be displayed exactly as capitalized on the new name submission.

A vast number of automatic name changes are submitted by the WOM RL plugin, which is currently leading to a lot of all lower-case names and therefore incorrect capitalization on the site which can't be corrected.

**Comment by dekvall** [comment]
Fixed by wise-old-man/wise-old-man#864
