### ISSUE TITLE
[Wise Old Man] - Plugin - Competitions

### ISSUE THREAD

**Issue by BoomOSRS** [dekvall/runelite-external-plugins#42]
**__Notifications__**
_Competition Notifications_ notifications are inconsistent with _Login info_ notifications.
![image](https://user-images.githubusercontent.com/70453840/133945093-684bdc33-d7d4-4f3e-8208-f2a7f4171802.png)
"Test has started!" should be "Competition Test has started!"

Also, perhaps `Competition: {comp name}` or `WOM Competition {comp name}` would be better than `Competition {comp name}` for these notifications.

**__Competition Timers__**
When a competition starts during a login session, the Upcoming Competition timer disappears, and the Ongoing timer does not appear until you relog or toggle this feature off and on. See gif here: <https://cdn.discordapp.com/attachments/696219254076342312/889268378664071168/YyoueTSq6Z.gif>

**Upcoming/Ongoing colour coding**
There's also no difference between the icon for 21:17 until a competition starts, and 21:17 until a competition ends. Perhaps they should be colour coded? Red numbers for upcoming or something?
The white text is also quite difficult to read without `Outline infobox text` turned on within the rl settings, particularly for a Slayer competition. This should be considered when choosing potential text colours for colour coding.

**Cluttered Infoboxes**
The infoboxes should be off by default, some members can be in multiple groups, and some clans run multiple competitions at the same time (for bingos, or dks competitions for example) This will get very messy/cluttered for users. After a quick check, I found this one user with 5 ongoing competitions, and 3 upcoming. That's 5-8 potential infoboxes which would be very crowded.
![image](https://user-images.githubusercontent.com/70453840/133945381-c3769ba1-5151-419b-bfc2-1ea5cd361e64.png)
I know eventually we'd like to add a ui for competitions within the plugin, it would be great to be able to individually toggle which competitions have an infobox if/when this becomes an option.

**Comment by dekvall** [comment]
Implemented by b8593276497ce24420725f10b8ffb9ca24b75be2
