### ISSUE TITLE
Fullscreen Borderless option request

### ISSUE THREAD

**Issue by QuinnoLinno** [dekvall/runelite-external-plugins#43]
Really good plugin I've been loving this a lot, but unfortunately with 2+ monitors this is a little frustrating as when I click off the game it gets minimized, and upon opening RS back up I need to disable the fullscreen option and re-enable it again. Having a fullscreen borderless option would be advantageous.

Thanks

**Comment by dekvall** [comment]
Added in 1582ba606b8d7d2b8903c047d2b7d8c81c9b4261
