### ISSUE TITLE
WOM - Useful links banner

### ISSUE THREAD

**Issue by Sethmare** [dekvall/runelite-external-plugins#47]
I got this idea from the "Bot Detector" plugin. They have a banner with some useful links at the top. Psikoi thinks this would look better at the bottom of the panel, unaffected by scrolling. Either way, I think it would be a good way for us to spread information about WOM and how to contribute/donate/troubleshoot.

![Screenshot_68](https://user-images.githubusercontent.com/66145237/147808697-87eb39b4-39b9-4e30-b299-d41807b4514b.png)

**Comment by dekvall** [comment]
Plugin has been moved to https://github.com/wise-old-man/wiseoldman-runelite-plugin
