### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by stankoviccc** [dekvall/runelite-external-plugins#5]
When i turn plugin on screen turns black

**Comment by dekvall** [comment]
Is this about the fullscreen plugin? I host a bunch of plugins in this repo. Also, would you mind sharing your logs located in `~/.runelite/logs`

**Comment by stankoviccc** [comment]
yes it's fullscreen plugin.i can't find logs file

**Comment by stankoviccc** [comment]
![penis](https://user-images.githubusercontent.com/67028976/84836996-3bbaa900-b037-11ea-8a9c-85dda8427248.PNG)
![penisx2](https://user-images.githubusercontent.com/67028976/84837003-4117f380-b037-11ea-9839-c7b9b35c2426.PNG)
Found it

**Comment by dekvall** [comment]
Great! Can you upload `client.log` and `launcher.log` here after a blackscreen.

**Comment by dekvall** [comment]
I'm closing this for now, please reopen with with the relevant information if it's still an issue.
