### ISSUE TITLE
doesn't work anymore I still see the empty option as of today

### ISSUE THREAD

**Issue by ghost** [dekvall/runelite-external-plugins#52]

**Comment by blakdragon39** [comment]
Same issue. Plugin doesn't seem to work since the inventory updates.

**Comment by BuzzfeedBlue** [comment]
Works for one computer, but not on another. Would love to see the dev update.

Also add the option for borderless fullscreen if possible / hotkey to toggle on and off

**Comment by dekvall** [comment]
Fixed in 7805fcafb2e79de32e8545788bd722a90b0261be
