### ISSUE TITLE
World Hider shows real world for a split second

### ISSUE THREAD

**Issue by pelletier2017** [dekvall/runelite-external-plugins#68]
Seen in this twitch clip of Alfie. When he switches to the world panel it shows the real world for a few frames. If you pause the video you can see he's at world 523 even though the fake world shows 330 afterwards. Snipers can take a clip just like this to hunt down streamers.

https://clips.twitch.tv/AltruisticHealthyFlyPraiseIt-sh5WrmELLedBFdBr

**Comment by dekvall** [comment]
Fixed in 08de4ad1a1534ea91cfa5255c601d7aee3718a6e
