### ISSUE TITLE
WOM: Add a warning if the group being synced isn't the same as the current group

### ISSUE THREAD

**Issue by rorro** [dekvall/runelite-external-plugins#75]
If you play on two accounts and are in a different clan in each account, you can accidentally override the group if you sync the group on the account that is not in your main clan. Adding a warning on sync if the clan being synced isn't the same group that is already synced on WOM.

This could possibly be done by checking the clan name (This won't work if the WOM group name isn't the same as the in-game clan name) or maybe checking that the clan owner is the same (This won't work if the clan ownership is transferred). 

A good option would be to check the amount of players being removed. If it's a completely different clan being synced, a lot of players would be removed by syncing.

**Comment by psikoi** [comment]
> If it's a completely different clan being synced, a lot of players would be removed by syncing.

if X percent of players differ, we can conclude it's a different clan and show a confirmation dialog, I'm not sure what an appropriate threshold would be, 50%?
