### ISSUE TITLE
[World Hider] mouseovertext shows selected world

### ISSUE THREAD

**Issue by oakland420** [dekvall/runelite-external-plugins#79]
just thought id let you know, when you hover over the world you want to hop to, even though the hider is on, it still shows the action on the top left of the screen of the actual world that you are hopping to, making it super easy for stream snipers

**Comment by dekvall** [comment]
I'll look into it. Though, I'm not sure that there is an easy fix for that on my end, but as a user, you can type `::mouseovertext` in the chat to disable the top-left text.

**Comment by ac0ff43** [comment]
bump still an issue @dekvall is it possible to fix this?

**Comment by dekvall** [comment]
Fixed by #87
