### ISSUE TITLE
Needs an update for Leagues 4

### ISSUE THREAD

**Issue by ShaunDreclin** [dekvall/runelite-external-plugins#88]
~~Plugin seems to be broken in trailblazer reloaded, it doesn't show the saved location on the map or change the inventory icon~~

Edit: It's only broken when used in Kourend

**Comment by dekvall** [comment]
Hi, thanks for the report. Would you mind sharing the chat message that is displayed when you store a zeah location?

**Comment by Yttrium-tYcLief** [comment]
> Hi, thanks for the report. Would you mind sharing the chat message that is displayed when you store a zeah location?

![image](https://github.com/dekvall/runelite-external-plugins/assets/1037011/eb888146-b0de-4171-aa67-4a4b0f742c81)

**Comment by dekvall** [comment]
Fixed in #91
