### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hejsherz** [dekvall/runelite-external-plugins#92]
Hello to you that made this amazing mod, in today on RL it seems when I logged on it doesn't store my last recall location anymore on my crystal of memories for some reason not working on league anymore sadly :/ 

-Last Recall plugin

**Comment by dekvall** [comment]
Fixed in 64b82501d7a2dd3d1e94b952f30716a7cb00c626

**Comment by hejsherz** [comment]
Thanks @dekvall works fine now in leagues again!
