### ISSUE TITLE
Suggestion/Idea: Last recall region flag on Fairy mushroom

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [dekvall/runelite-external-plugins#93]
Hello, first of all thank you for the plugin, very handy! So handy that it would be extra handy if the little region flag that appears on the crystal also appeared on the Fairy mushroom for the purposes of using the "Last-destination" right click option.

tldr: add option to show the region flag on the Fairy mushroom so its more obvious where it would take you.

**Comment by dekvall** [comment]
Hi, thanks for the nice words.
Sorry, but for this particular plugin, features related to other relics and/or items are out of scope.
