### ISSUE TITLE
Resource Pack problems

### ISSUE THREAD

**Issue by verafeiyd** [dekvall/runelite-external-plugins#95]
I didnt necessarily want to create an issue for this as its more so my packs that have a problem, not the plugin, but I'm desparately wondering what makes up this asset because it is not working correctly and I'd like to fix it, assuming it doesnt break anything else in the resource pack 

[![image](https://github.com/dekvall/runelite-external-plugins/assets/123139321/a1780246-b9a0-4d7f-b4e7-bfaeca91f719)](url)

**Comment by dekvall** [comment]
Hi,
So the logout button is basically three sprites, and all of them are being scaled when making the button bigger (code below).
https://github.com/dekvall/runelite-external-plugins/blob/4b8bd37a5ea0969f5e24b08e6ee2e7222d96a699/src/main/java/dev/dkvl/largelogout/LargeLogoutPlugin.java#L155-L171 

I am not familiar with how resource packs works, but maybe all three need to be replaced for it to work as expected. Unfortunately, there is not much more I can do on my end than refer you to the resource-pack repo.

Thanks for reaching out!
